"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  BookOpen,
  Search,
  Sparkles,
  ArrowRight,
  Eye,
  Calendar,
  User,
  TrendingUp,
} from "lucide-react";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { useStore } from "@/lib/store-context";
import { useI18n } from "@/lib/i18n";
import { formatNumber } from "@/lib/utils";

export default function BlogListingPage() {
  const { language, articles } = useStore();
  const t = useI18n(language);

  const [query, setQuery] = useState("");

  const filteredArticles = articles.filter((art) => {
    const title = language === "en" ? art.title.en : art.title.id;
    const excerpt = language === "en" ? art.excerpt.en : art.excerpt.id;
    return (
      title.toLowerCase().includes(query.toLowerCase()) ||
      excerpt.toLowerCase().includes(query.toLowerCase()) ||
      art.focusKeyword.toLowerCase().includes(query.toLowerCase())
    );
  });

  return (
    <div className="min-h-screen flex flex-col bg-slate-50 dark:bg-slate-950">
      <Navbar />

      <main className="flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-10 space-y-8">
        {/* Blog Hero Banner */}
        <div className="text-center space-y-3 max-w-2xl mx-auto">
          <Badge variant="purple" className="text-xs">
            Wospy SEO Engine Blog
          </Badge>
          <h1 className="text-3xl sm:text-4xl font-black text-slate-900 dark:text-white">
            {language === "en"
              ? "International Trade & SEO Insights"
              : "Wawasan Ekspor & Artikel SEO Praktis"}
          </h1>
          <p className="text-sm text-slate-500 leading-relaxed">
            {language === "en"
              ? "Explore high-ranking SEO content generated by Wospy AI. Case studies, buyer sourcing guides, and trade compliance."
              : "Kumpulan artikel SEO berkualitas tinggi yang dihasilkan oleh AI Wospy untuk mendatangkan traffic buyer organik."}
          </p>
        </div>

        {/* Search */}
        <div className="max-w-md mx-auto">
          <div className="relative">
            <Search className="absolute left-3.5 top-3 h-4 w-4 text-slate-400" />
            <Input
              placeholder="Cari artikel, panduan, atau kata kunci..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="pl-10 h-11 text-xs bg-white dark:bg-slate-900 shadow-sm"
            />
          </div>
        </div>

        {/* Articles Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredArticles.map((art) => {
            const title = language === "en" ? art.title.en : art.title.id;
            const excerpt = language === "en" ? art.excerpt.en : art.excerpt.id;

            return (
              <Card key={art.id} className="overflow-hidden hover:shadow-lg transition-all flex flex-col justify-between group">
                <div>
                  <div className="relative h-48 w-full overflow-hidden bg-slate-100">
                    <img
                      src={art.featuredImage}
                      alt={art.imageAlt || title}
                      className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
                    />
                    <div className="absolute top-3 left-3">
                      <Badge variant="success" className="text-[10px] shadow backdrop-blur-sm bg-slate-900/80 text-emerald-400 border-0">
                        {art.views} Views
                      </Badge>
                    </div>
                  </div>

                  <div className="p-5 space-y-3">
                    <div className="flex items-center space-x-2 text-[11px] text-slate-400">
                      <span>{art.publishDate}</span>
                      <span>•</span>
                      <span>By {art.author}</span>
                    </div>

                    <h2 className="text-base font-bold text-slate-900 dark:text-white line-clamp-2 leading-snug group-hover:text-blue-600 transition-colors">
                      <Link href={`/blog/${art.slug}`}>
                        {title}
                      </Link>
                    </h2>

                    <p className="text-xs text-slate-500 dark:text-slate-400 line-clamp-3 leading-relaxed">
                      {excerpt}
                    </p>
                  </div>
                </div>

                <div className="p-5 pt-0 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs">
                  <span className="font-semibold text-blue-600 dark:text-blue-400 font-mono">
                    /{art.slug}
                  </span>
                  <Link href={`/blog/${art.slug}`}>
                    <Button variant="ghost" size="sm" className="h-8 text-xs font-semibold hover:text-blue-600">
                      <span>Baca Selengkapnya</span>
                      <ArrowRight className="h-3.5 w-3.5 ml-1" />
                    </Button>
                  </Link>
                </div>
              </Card>
            );
          })}
        </div>
      </main>

      <Footer />
    </div>
  );
}
