export type SalesPageInput = {
  product: string;
  audience: string;
  price: string;
  originalPrice: string;
  cta: string;
};

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char] ?? char);

export function buildSalesPageHtml(input: SalesPageInput) {
  const product = escapeHtml(input.product || "797 Template Iklan High-Conversion");
  const audience = escapeHtml(input.audience || "pemilik bisnis dan marketer Indonesia");
  const price = escapeHtml(input.price || "Rp149.000");
  const originalPrice = escapeHtml(input.originalPrice || "Rp1.497.000");
  const cta = escapeHtml(input.cta || "AMBIL SEMUA TEMPLATE SEKARANG");
  const asset = "https://kreava-ai-studio.kpm-den-6447.chatgpt.site/templates";

  return `<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${product}</title>
  <meta name="description" content="Koleksi template iklan siap pakai untuk membuat promosi lebih cepat dan lebih menjual.">
  <style>
    :root{--ink:#10251f;--paper:#fffaf1;--orange:#ff5a36;--lime:#d7ff4f;--line:#dce4df;--muted:#61706a;--white:#fff;--max:1160px}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--paper);font-family:Inter,Arial,Helvetica,sans-serif;font-size:19px;line-height:1.65}.wrap{width:min(var(--max),calc(100% - 40px));margin:auto}h1,h2,h3,p{margin-top:0}h1{font-size:clamp(44px,7vw,82px);line-height:.98;letter-spacing:-.055em}h2{font-size:clamp(34px,5vw,58px);line-height:1.05;letter-spacing:-.04em}h3{font-size:25px;line-height:1.2}.eyebrow{font-size:14px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;color:var(--orange)}.muted{color:var(--muted)}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:62px;padding:14px 28px;border-radius:12px;background:var(--orange);color:#fff;text-decoration:none;font-size:18px;font-weight:900;box-shadow:0 12px 30px #ff5a3640}.btn:hover{background:#e84725;transform:translateY(-1px)}.btn small{font-size:13px;margin-left:12px;opacity:.8}.top-alert{padding:10px 16px;background:var(--lime);text-align:center;font-size:14px;font-weight:900}.hero{padding:82px 0 70px;background:var(--ink);color:#fff;overflow:hidden}.hero-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:60px;align-items:center}.hero h1 span{color:var(--lime)}.hero-copy{font-size:21px;color:#d5dfdb;max-width:650px}.proof{display:flex;gap:22px;flex-wrap:wrap;margin:25px 0}.proof span{font-size:14px;font-weight:800}.proof b{color:var(--lime)}.hero-card{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:10px;transform:rotate(2deg)}.hero-card img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:14px;border:4px solid #fff;box-shadow:0 25px 55px #0006}.hero-card img:nth-child(2){transform:translateY(25px)}.float-label{position:absolute;right:-10px;bottom:-22px;padding:12px 16px;border-radius:10px;background:var(--orange);color:#fff;font-size:14px;font-weight:900;transform:rotate(-4deg)}
    section{padding:92px 0}.center{text-align:center}.narrow{max-width:820px;margin-inline:auto}.pain-grid,.benefit-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:42px}.pain-card,.benefit{padding:28px;border:1px solid var(--line);border-radius:18px;background:#fff}.pain-card i{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:#ffe9e2;color:var(--orange);font-style:normal;font-weight:900}.agitate{background:#f0f2ef}.agitate blockquote{margin:38px auto 0;max-width:920px;padding:35px 40px;border-left:8px solid var(--orange);background:#fff;font-size:clamp(25px,3.5vw,42px);font-weight:850;line-height:1.18;letter-spacing:-.025em}.solution{background:#fff}.gallery{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;margin:45px 0}.gallery img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:14px;box-shadow:0 15px 32px #17322918}.benefit b{display:block;color:var(--orange);font-size:14px;margin-bottom:8px}.offer{background:var(--ink);color:#fff}.offer-box{display:grid;grid-template-columns:1fr .82fr;gap:50px;align-items:center}.stack{padding:30px;border:1px solid #ffffff24;border-radius:20px;background:#ffffff0c}.stack-row{display:flex;justify-content:space-between;gap:20px;padding:15px 0;border-bottom:1px solid #ffffff1c}.stack-row:last-child{border:0}.stack-row span{color:#d6dfdb}.price s{color:#9eaaa5;font-size:23px}.price strong{display:block;color:var(--lime);font-size:56px;line-height:1}.scarcity{margin:20px 0;padding:13px;border-radius:10px;background:#ff5a3620;color:#ffb39f;font-size:15px;font-weight:850}.testimonial-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:40px}.quote{padding:28px;border-radius:17px;background:#fff;border:1px solid var(--line)}.stars{color:#f49b19;letter-spacing:2px}.guarantee{display:flex;gap:25px;align-items:center;max-width:800px;margin:60px auto 0;padding:28px;border-radius:18px;background:#eef7ef}.seal{flex:none;width:90px;height:90px;border-radius:50%;display:grid;place-items:center;background:var(--ink);color:var(--lime);font-weight:900;text-align:center;font-size:13px}.final-cta{padding-bottom:135px;background:var(--orange);color:#fff;text-align:center}.final-cta .btn{background:var(--ink);box-shadow:none}.sticky-buy{position:fixed;left:0;right:0;bottom:0;z-index:20;padding:12px 20px;background:#fff;border-top:1px solid var(--line);box-shadow:0 -10px 30px #10251f1c}.sticky-inner{width:min(var(--max),100%);margin:auto;display:flex;align-items:center;justify-content:space-between;gap:20px}.sticky-price span{display:block;color:var(--muted);font-size:12px}.sticky-price strong{font-size:23px}.sticky-buy .btn{min-height:52px;padding:10px 24px}.safe{font-size:13px;color:var(--muted);margin:12px 0 0}
    @media(max-width:820px){body{font-size:18px}.wrap{width:min(100% - 28px,var(--max))}.hero{padding-top:58px}.hero-grid,.offer-box{grid-template-columns:1fr}.hero-card{max-width:520px}.pain-grid,.benefit-grid,.testimonial-grid{grid-template-columns:1fr}.gallery{grid-template-columns:1fr 1fr}section{padding:68px 0}.offer-box{gap:32px}.sticky-price{display:none}.sticky-buy .btn{width:100%}.agitate blockquote{padding:25px}.guarantee{align-items:flex-start}.seal{width:72px;height:72px}}
  </style>
</head>
<body>
  <div class="top-alert">🔥 HARGA LAUNCH BERAKHIR MALAM INI — Jangan bayar lebih mahal besok.</div>
  <header class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">Untuk ${audience}</p><h1>Stop menebak desain iklan. <span>Pakai yang sudah siap menjual.</span></h1><p class="hero-copy">Dapatkan ${product}: koleksi visual promosi yang membuat orang berhenti scroll, memahami penawaranmu, lalu terdorong untuk membeli.</p><div class="proof"><span><b>797</b> desain unik</span><span><b>7</b> formula konversi</span><span><b>100%</b> siap pakai</span></div><a href="#" class="btn">${cta} <small>→</small></a><p class="safe">✓ Sekali bayar &nbsp; ✓ Akses langsung &nbsp; ✓ Bisa disesuaikan</p></div><div class="hero-card"><img src="${asset}/t0115.jpg" alt="Contoh template iklan"><img src="${asset}/t0482.jpg" alt="Contoh materi promosi"><span class="float-label">797 desain siap pakai</span></div></div></header>
  <section><div class="wrap center"><p class="eyebrow">Masalah sebenarnya</p><h2 class="narrow">Produkmu mungkin bagus. Tapi iklan yang terlihat biasa akan terus dilewati.</h2><div class="pain-grid"><article class="pain-card"><i>1</i><h3>Ide habis terus</h3><p class="muted">Setiap hari harus posting, tetapi layar kosong dan deadline semakin dekat.</p></article><article class="pain-card"><i>2</i><h3>Desain tidak meyakinkan</h3><p class="muted">Pesan berantakan membuat calon pembeli ragu sebelum membaca penawaranmu.</p></article><article class="pain-card"><i>3</i><h3>Biaya iklan terbuang</h3><p class="muted">Traffic datang, tetapi visual yang lemah gagal menghentikan scroll dan menciptakan klik.</p></article></div></div></section>
  <section class="agitate"><div class="wrap center"><p class="eyebrow">Dan ini yang menyakitkan...</p><h2>Setiap iklan yang diabaikan adalah calon pelanggan yang pergi ke kompetitor.</h2><blockquote>“Bukan produknya yang tidak laku. Bisa jadi, calon pembeli belum pernah melihat produkmu disajikan dengan cara yang membuat mereka ingin punya.”</blockquote></div></section>
  <section class="solution"><div class="wrap center"><p class="eyebrow">Solusinya sudah di depan mata</p><h2 class="narrow">Pilih. Sesuaikan. Publikasikan. Tidak perlu mulai dari nol lagi.</h2><p class="narrow muted">Koleksi ini dirancang dari berbagai pola iklan: promo, edukasi, testimoni, urgensi, pain–solution, hingga peluncuran produk.</p><div class="gallery"><img src="${asset}/t0237.jpg" alt="Template promosi"><img src="${asset}/t0341.jpg" alt="Template testimoni"><img src="${asset}/t0575.jpg" alt="Template diskon"><img src="${asset}/t0712.jpg" alt="Template edukasi"></div><div class="benefit-grid"><article class="benefit"><b>LEBIH CEPAT</b><h3>Konten siap dalam hitungan menit</h3><p class="muted">Lewati proses mencari ide dan menyusun layout dari awal.</p></article><article class="benefit"><b>LEBIH MEYAKINKAN</b><h3>Struktur visual yang jelas</h3><p class="muted">Headline, manfaat, bukti, dan CTA tampil dalam urutan yang mudah dipahami.</p></article><article class="benefit"><b>LEBIH KONSISTEN</b><h3>Selaras dengan brand-mu</h3><p class="muted">Ganti warna, font, gambar, dan copy tanpa kehilangan struktur desain.</p></article></div></div></section>
  <section class="offer"><div class="wrap offer-box"><div><p class="eyebrow">Penawaran sekali bayar</p><h2>Semua yang kamu butuhkan untuk berhenti membuat iklan dari nol.</h2><p class="muted">Gunakan untuk berbagai produk, kampanye, dan niche. Koleksi terus bisa kamu jadikan referensi visual.</p></div><div class="stack"><div class="stack-row"><span>797 template iklan 1:1</span><b>Rp997.000</b></div><div class="stack-row"><span>Kategori high-conversion</span><b>Rp250.000</b></div><div class="stack-row"><span>Hak pakai komersial</span><b>Rp250.000</b></div><div class="price"><s>Total nilai ${originalPrice}</s><strong>${price}</strong></div><div class="scarcity">⏳ Harga khusus hanya untuk 50 pembeli berikutnya.</div><a href="#" class="btn">${cta}</a></div></div></section>
  <section><div class="wrap center"><p class="eyebrow">Sudah dipakai untuk bergerak lebih cepat</p><h2>Bukan sekadar cantik. Dibuat untuk mempermudah orang berkata “ya”.</h2><div class="testimonial-grid"><article class="quote"><div class="stars">★★★★★</div><p>“Dulu satu desain bisa habis satu jam. Sekarang tinggal pilih konsep dan sesuaikan. Konten seminggu selesai dalam satu sore.”</p><b>— Rina, pemilik brand skincare</b></article><article class="quote"><div class="stars">★★★★★</div><p>“Yang paling membantu adalah variasi angle-nya. Tim tidak lagi mengulang desain yang sama setiap promo.”</p><b>— Aldi, performance marketer</b></article><article class="quote"><div class="stars">★★★★★</div><p>“Visual promo kami jadi lebih rapi dan jelas. Pelanggan langsung paham produk, harga, dan tombol belinya.”</p><b>— Maya, seller online</b></article></div><div class="guarantee"><div class="seal">7 HARI<br>GARANSI</div><div><h3>Coba tanpa rasa khawatir.</h3><p class="muted">Jika koleksi tidak sesuai dengan deskripsi, hubungi kami dalam 7 hari untuk evaluasi pengembalian dana.</p></div></div></div></section>
  <section class="final-cta"><div class="wrap"><p class="eyebrow" style="color:#fff">Jangan biarkan ide bagus terlihat biasa</p><h2>Besok kamu tetap butuh konten.<br>Bedanya, kamu bisa mulai dengan 797 pilihan.</h2><a href="#" class="btn">${cta}</a></div></section>
  <div class="sticky-buy"><div class="sticky-inner"><div class="sticky-price"><span>Harga launch hari ini</span><strong>${price}</strong></div><a href="#" class="btn">${cta}</a></div></div>
</body>
</html>`;
}
